### ISSUE TITLE
Deploy MongoDB on Dev using an operator

### ISSUE THREAD

**Issue by akkbng** [mindtastic/deployments#11]
Deploy MongoDB using a kubernetes operator. 

- MongoDB has an officially maintained [kubernetes operator for MongoDB community](https://github.com/mongodb/mongodb-kubernetes-operator). This operator can be used to install and deploy MongoDB in our cluster.

**Comment by akkbng** [comment]
Two different options for deploying MongoDB Community is provided in the [documentation](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md). These options are installing the operator using Helm and using kubectl. 

- Do you have a recommendation or preference for which option to use? @ldb @jgraeger @isaschm

**Comment by ldb** [comment]
I'd say Helm :)
