### ISSUE TITLE
Make authentication secure

### ISSUE THREAD

**Issue by ldb** [mindtastic/deployments#14]
Right now Kratos is published using an ingress without a valid SSL certificate.
This must be fixed. Two ways to do this:
- create a long lived wildcard certificate and put it into [Google Certificate Manager](https://cloud.google.com/certificate-manager/docs/overview) to attach it to the ingress
-  Deploy [cert-manager](https://cert-manager.io/docs/) or something alike to create certificates on demand

**Comment by jgraeger** [comment]
I guess [Traefik](https://doc.traefik.io/traefik/https/acme/) will handle this, as soon as we deployed it.

**Comment by ldb** [comment]
Yes, but not globally. Only endpoints behind Traefik would benefit from this. Apart from that, SSL offloading would shift into the Cluster instead of being handled by the Load Balancers in GCP. This is not a big problem at our scale yet, but something to bear in mind.
