### ISSUE TITLE
Deploy Postgres using an operator

### ISSUE THREAD

**Issue by theEpsilon** [mindtastic/deployments#3]
Postgres should be deployed using a Kubernetes operator, such as [Crunchy](https://access.crunchydata.com/documentation/postgres-operator/latest/).

This method has advantages in terms of administration, maintainance and security.

Issue can be closed once:

- [ ] PGO manages the Postgres cluster
- [x] ~~Postgres communicates with Keycloak~~

**Comment by jgraeger** [comment]
I removed the "Communication with Keycloak" as an acceptance criteria, since we agreed on first deploying a usable postgres instance to the cluster and then handle Keycloak in a seperate issue.
